accounts/urls.py
from django.contrib.auth.views import logout
from django.urls import re_path
from .views import *

urlpatterns = [
    re_path(r'^send_login_email$', send_login_email, name='send_login_email'),
    re_path(r'^login$', login, name='login'),
    re_path(r'^logout$', logout, {'next_page': '/'}, name='logout',)
]

lists/urls.py
from django.contrib import admin
from django.urls import path, re_path

from lists import views

urlpatterns = [
    re_path(r'^new$', views.new_list, name='new_list'),
    re_path(r'^(\d+)/$', views.view_list, name='view_list'),
    re_path(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from lists import urls as lists_urls
from accounts import urls as accounts_urls
from lists import views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.home_page, name='home'),
    re_path(r'^lists/', include(lists_urls)),
    re_path(r'^accounts/', include(accounts_urls)),
]

accounts/models.py
import uuid
from django.db import models
from django.contrib import auth

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    email = models.EmailField(unique=True, primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.urls import reverse
from django.db import models
from django.conf import settings


class List(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        lst = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=lst)
        return lst

    @property
    def name(self):
        return self.item_set.first().text


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Item, List

EMPTY_ITEM_ERROR = 'You cannot have an empty list item'
DUPLICATED_ITEM_ERROR = 'You have already got this item in your list'


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(
                attrs={
                    'placeholder': 'Enter a to-do item',
                    'class': 'form-control input-lg',
                }
            ),
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATED_ITEM_ERROR]}
            self._update_errors(e)


class NewListForm(ItemForm):

    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(
                first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(
                first_item_text=self.cleaned_data['text'])

accounts/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib import auth, messages

from .models import Token


def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + '?token=' + str(token.uid)
    )
    message_body = f'Use this link to login:\n\n{url}'
    send_mail(
        'Your login link for Superlists',
        message_body,
        'noreply@superlists.com',
        [email],
    )
    messages.success(
        request,
        'Check your email, we have sent you a link you can use to login.'
    )
    return redirect('/')


def login(request):
    uid = request.GET.get('token')
    user = auth.authenticate(uid=uid)
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from .models import Item, List
from .forms import (
    ItemForm,
    ExistingListItemForm,
    NewListForm,
)
User = get_user_model()


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        lst = form.save(owner=request.user)
        return redirect(lst)
    return render(request, 'home.html', {'form': form})


def view_list(request, list_id):
    lst = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=lst)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=lst, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(lst)
    return render(request, 'list.html', {'list': lst, 'form': form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

lists/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>To-Do Lists</title>
        <link href="/../static/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="container"> 
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <a href="/" class="navbar-brand">Superlists</a>
                    {% if user.email %}
                        <ul class="nav navbar-nav navbar-left">
                            <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="navbar-text">Logged in as {{ user.email }}</li>
                            <li><a href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    {% else %}    
                            <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
                                <span>Enter email to login:</span>
                                <input class="form-control" name="email" type="text" />
                                {% csrf_token %}
                            </form>
                    {% endif %}
                </div>
            </nav>
            
            {% if messages %}
                <div class="row">
                    <div class="col-md-8">                        
                        {% for message in messages %}                            
                            {% if message.level_tag == 'success' %}
                                <div class="alert alert-success">{{ message }}</div>
                            {% else %}
                                <div class="alert alert-warning">{{ message }}</div>
                            {% endif %}                                
                        {% endfor %}                            
                    </div>
                </div>
            {% endif %}
                
            <div class="row justify-content-md-center">
                <div class="col jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock %}</h1>                        
                        {% block list_form %}
                            <form method="POST" action="{% block form_action %}{% endblock %}">
                                {{ form.text }}
                                {% csrf_token %}
                                {% if form.errors %}
                                    <div class="form-group has-danger">
                                        <span class="help-block">{{ form.text.errors }}</span>
                                    </div>
                                {% endif %}
                            </form>
                        {% endblock list_form %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block table %}
                    {% endblock table %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block extra_content %}
                    {% endblock extra_content %}
                </div>
            </div>
        </div>
        <script src="../static/js/jquery-3.3.1.min.js"></script>
        <script src="../static/js/lists.js"></script>
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}


{% block header_text %}
    Start a new To-Do
{% endblock header_text %}


{% block form_action %}
    {% url 'new_list' %}
{% endblock form_action %}
    
    

lists/templates/list.html
{% extends "base.html" %}


{% block header_text %}
    Your To-Do list
{% endblock header_text %}


{% block form_action %}
    {% url 'view_list' list.id %}
{% endblock form_action %}


{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock table %}

lists/templates/my_lists.html
{% extends 'base.html' %}


{% block header_text %}
    My Lists
{% endblock header_text %}

{% block list_form %}
{% endblock list_form %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
        {% endfor %}
    </ul>
{% endblock extra_content %}

superlists/lists/templates/home.html
<html>
    <head>
        <title>To-Do Lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form method='POST'>
            <input id='id_new_item' name='item_text' placeholder='Enter a to-do item'/>{% csrf_token %}
        </form>
        <table id='id_list_table'>
            {% for item in items %}
            <tr>
                <td>{{ forloop.counter }}: {{ item.text }}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>